baseURL: "https://mjvo.github.io/vms564s"
title: "VMS 564S"

defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1

MetaDataFormat: "yaml"

theme: 
  - "hugo-course"
  - "reveal-hugo"

FootnoteReturnLinkContents: "↩"

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true

params:
  course:
    name: "Physical Computing & the Internet of Things"
    dept_url: "https://aahvs.duke.edu"
    dept_logo: "/images/AAHVS_Barcode_Logo.png"
    day_time: "Tuesdays & Thursdays, 8:30 - 9:45 AM"
    location: "A290 Smith Warehouse, Bay 9"
    hero_img: "/images/arduino.png"
    hero_img_credit: 
    
  reveal_hugo:
    theme: white
    
    width: 960
    height: 540
    margin: 0.1
    min_scale: .1
    max_scale: 1

    highlight_theme: "atom-one-dark"
    menu:
      open_button: false